### ISSUE TITLE
New comment system

### ISSUE THREAD

**Issue by lazywinadmin** [lazywinadmin/lazywinadmin.github.io#8]
## Type

* [ ] Issue
* [ ] Feature
* [x] Change

## Description

Currently the website is using Disqus to manage the Comments (which is an external system)

I'd like to bring the comment closer to the blog content.
There are few options available to me:

* Using Static files and PR to add new comments (staticman/Azure Function)
* Using Github Issues API (utterances)

## Static files
Taking the static file approach is cool but there are some limitations to solution like StaticMan: No notification built-in, no conversation support,... (see here if you want to add it to your blog [here](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860)). 

See also:
 * https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/
* https://www.datascienceblog.net/post/other/staticman_comments/

Another option would be to use Azure Function, see: https://damieng.com/blog/2018/05/28/wordpress-to-jekyll-comments but it seems a bit complicated to put in place (escuse my novice knowledge)

Pros:
* Live with the code
* Spam can be filtered out using ReCaptcha
* Can be exported and manipulated easily

Cons:
* No notification, would need to register to mailgun (limit of 10k mails)
* No conversation

## Github issues api

Using Github issues as comment system seems pretty simple with my current blog theme. Different frameworks exists:
* https://github.com/utterance/utterances
* https://github.com/imsun/gitment

Pros:
* No spam
* integrated with Github
* Notifications take care of
* conversation support
* Can be exported via API

Cons:
* Another dependency
* Must have a github account to comment (pros?)

**Comment by lazywinadmin** [comment]
Implemented and configured in #11

**Comment by lazywinadmin** [comment]
https://asp.net-hacker.rocks/2018/11/19/github-comments.html
https://github.com/utterance/utterances/issues/7
https://github.com/JuergenGutsch/blog/issues/110

**Comment by lazywinadmin** [comment]
Utterances looks very nice but does not support importing historical comments

**Comment by JuergenGutsch** [comment]
This is why I created a small Disqus to GitHub migration tool: https://github.com/JuergenGutsch/disqus-to-github-issues

**Comment by lazywinadmin** [comment]
Thanks @JuergenGutsch !! A bit too late hehe 😄  I actually went through the same process and wrote a tool in PowerShell script

**Comment by lazywinadmin** [comment]
This was implemented. I'm using Github issues with Utterances.
See related blogpost: https://lazywinadmin.com/2019/04/moving_blog_comments.html
